## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [1]:
import pandas as pd
from pandas.conftest import observed

In [2]:
# загружаем датасет
data = pd.read_csv("./data/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [4]:
# your code
counts = data['sex'].value_counts()
counts

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [10]:
# your code
average_male_age = data[data['sex'] == 'Male']['age'].mean()
average_male_age

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [11]:
# your code
percentage_US = data[data['native-country'] == 'United-States'].shape[0] / data.shape[0] * 100
percentage_US

89.5857006848684

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [15]:
# your code
data.groupby('salary')['age'].agg(['mean', 'std'])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [24]:
# your code
higher_education = [
    'Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate'
]
# True -> means all have high education, False -> opposite
data[(data['salary'] == '>50K') & (~data['education'].isin(higher_education))].empty

False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [45]:
# your code
desciptive_race_stat = data.groupby(['race', 'sex'])['age'].describe()
desciptive_race_stat.loc[('Asian-Pac-Islander', 'Male'), 'max']

np.float64(90.0)

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [67]:
# your code
men = data[data['sex'] == 'Male'].copy()
men['married'] = men['marital-status'].str.startswith('Married')
income_share = men.groupby('married')['salary'].apply(lambda x: (x == '>50K').mean())
(income_share * 100).round(2)

married
False     8.45
True     44.05
Name: salary, dtype: float64

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [83]:
# your code
max_hours = data['hours-per-week'].max()
people_with_max_hours = data[data['hours-per-week'] == max_hours]
wealthy_people_with_max_hours = people_with_max_hours[people_with_max_hours['salary'] == '>50K']
print(f'Max hours per week: {max_hours},\n'
      f'Number of people with max hours in a week: {people_with_max_hours.size},\n'
      f'Percentage of those people who earn more: {wealthy_people_with_max_hours.size / people_with_max_hours.size * 100}')

Max hours per week: 99,
Number of people with max hours in a week: 1275,
Percentage of those people who earn more: 29.411764705882355

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [85]:
# your code
by_countries = data.groupby(['native-country', 'salary'])['hours-per-week'].mean()
by_countries

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [93]:
# your code
copy = data.copy()
bins = [16, 35, 70, 100]
labels = ['young', 'adult', 'retiree']
copy['AgeGroup'] = pd.cut(copy['age'], bins=bins, labels=labels, right=True, include_lowest=True)
copy.groupby('AgeGroup', observed=True).size()

AgeGroup
young      14925
adult      17096
retiree      540
dtype: int64

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [105]:
# your code
high_income = copy[copy['salary'] == '>50K']
high_income_counts = high_income.groupby('AgeGroup', observed=True).size().rename('Counts')
high_income_counts.idxmax()

'adult'

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [122]:
# your code
occupations_counts = data.groupby('occupation').size().reset_index(name='Count')

def filter_func(group):
    return (group['age'].mean() <= 40) and (group['hours-per-week'].min() > 5)

filtered_groups = data.groupby('occupation', observed=True).filter(filter_func)

valid_occupations = filtered_groups['occupation'].unique()
valid_occupations

array(['Armed-Forces'], dtype=object)

In [123]:
occupations_counts

           occupation  Count
0                   ?   1843
1        Adm-clerical   3770
2        Armed-Forces      9
3        Craft-repair   4099
4     Exec-managerial   4066
5     Farming-fishing    994
6   Handlers-cleaners   1370
7   Machine-op-inspct   2002
8       Other-service   3295
9     Priv-house-serv    149
10     Prof-specialty   4140
11    Protective-serv    649
12              Sales   3650
13       Tech-support    928
14   Transport-moving   1597